[tools]
python = "{{ get_env(name='PYTHON_VERSION', default='3.12') }}"
node = "22"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks."allure:serve"]

description = "Download Allure results from GitLab pipeline and serve them"

usage = '''

'''

#Optional flags:
#--outdir <name>    Save under out/<name>
#--use-tmp-dir      Use a temporary directory
#--serve-only <dir> Serve existing allure results and exit

run = [
'npm install --global allure-commandline',
'pip install -r scripts/requirements.txt',
'python scripts/allure_serve.py'
]